folio-org/mod-consortia

Jenkinsfile

[MODFISTO-393] - Jenkinsfile updated

---

pom.xml
src/main/java/org/folio/consortia/FolioConsortiaApplication.java
src/main/java/org/folio/consortia/controller/HealthCheckController.java
src/test/java/org/folio/consortia/FolioConsortiaApplicationTest.java
src/test/java/org/folio/consortia/context/PostgresTestContainersBeanFactoryPostProcessor.java
src/test/java/org/folio/consortia/controller/HealthCheckControllerTest.java
src/test/java/org/folio/consortia/support/BaseTest.java

[MODFISTO-393] - Added HealthCheckController

---

src/main/resources/db/changelog/changes/create-tenant-table.xml
src/main/resources/db/changelog/changes/create-user-tenant-table.xml

[MODFISTO-400-2]-updated schema for tenant and user_tenant table .

---

src/main/resources/db/changelog/changelog-master.xml
src/main/resources/db/changelog/changes/create-consortium-table.xml
src/main/resources/db/changelog/changes/create-user-tenant-table.xml

https://issues.folio.org/browse/MODCON-18 …

[MODCON-18]-Added consortium table.

---

README.md

Update README file
While it's helpful …

[MODCON-1-docs]-updated README.md

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/consortia/controller/ErrorHandlingController.java
src/main/java/org/folio/consortia/controller/UserTenantController.java
src/main/java/org/folio/consortia/exception/PrimaryAffiliationException.java
src/main/java/org/folio/consortia/repository/UserTenantRepository.java
src/main/java/org/folio/consortia/service/UserTenantService.java
src/main/java/org/folio/consortia/service/impl/UserTenantServiceImpl.java
src/main/resources/swagger.api/user_tenants.yaml
src/test/java/org/folio/consortia/controller/UserTenantControllerTest.java
src/test/java/org/folio/consortia/service/UserTenantServiceTest.java

https://issues.folio.org/browse/MODCON-12 …

[MODCON-12] - Implement endpoint to remove user association from a tenant

---

PERSONAL_DATA_DISCLOSURE.md

PERSONAL_DATA_DISCLOSURE

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/consortia/controller/ErrorHandlingController.java
src/main/java/org/folio/consortia/service/impl/UserTenantServiceImpl.java

- Logging for create/delete affiliation improved
- Permission sets corrected

[MODCON-11] Misc fixes after testing on rancher and improve logging

---

src/main/java/org/folio/consortia/service/UserTenantService.java
src/main/java/org/folio/consortia/service/impl/UserAffiliationServiceImpl.java
src/main/java/org/folio/consortia/service/impl/UserTenantServiceImpl.java
src/test/java/org/folio/consortia/service/UserAffiliationServiceTest.java
src/test/java/org/folio/consortia/service/UserTenantServiceTest.java

https://issues.folio.org/browse/MODCON-32 …

[MODCON - 32 - 1] - Fixed cycle of nonstop creating primary affiliation by listener

---

src/main/java/org/folio/consortia/controller/ErrorHandlingController.java
src/main/java/org/folio/consortia/domain/entity/TenantEntity.java
src/main/java/org/folio/consortia/repository/TenantRepository.java
src/main/java/org/folio/consortia/service/impl/TenantServiceImpl.java
src/main/java/org/folio/consortia/service/impl/UserAffiliationServiceImpl.java
src/main/resources/application.yml
src/main/resources/swagger.api/schemas/tenant.yaml
src/test/java/org/folio/consortia/controller/TenantControllerTest.java
src/test/java/org/folio/consortia/service/TenantServiceTest.java
src/test/java/org/folio/consortia/service/UserAffiliationServiceTest.java

https://issues.folio.org/browse/MODCON-64
We are moving validation to the Controller layer it gives more convenience with transactions and better performance
example response
to avoid breaking the folio-testing …

[MODCON-64] - Fixed transaction behaviour of saving tenant method

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/consortia/controller/PublicationController.java
src/main/java/org/folio/consortia/repository/PublicationTenantRequestRepository.java
src/main/java/org/folio/consortia/service/PublicationService.java
src/main/java/org/folio/consortia/service/impl/PublicationServiceImpl.java
src/main/resources/swagger.api/publications.yaml
src/main/resources/swagger.api/schemas/publication_schema.yaml
src/test/java/org/folio/consortia/controller/PublicationControllerTest.java
src/test/java/org/folio/consortia/utils/EntityUtils.java

* https://issues.folio.org/browse/MODCON-49
* implemented get publication details …

MODCON-49 implemented get publication details

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/consortia/controller/PublicationController.java
src/main/java/org/folio/consortia/service/PublicationService.java
src/main/java/org/folio/consortia/service/impl/PublicationServiceImpl.java
src/main/resources/swagger.api/publications.yaml
src/main/resources/swagger.api/schemas/publication_schema.yaml
src/test/java/org/folio/consortia/controller/PublicationControllerTest.java

https://issues.folio.org/browse/MODCON-56
* implemented get publication results …

MODCON-56 implemented get publication results

---

descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/consortia/client/InventoryClient.java
src/main/java/org/folio/consortia/service/InventoryService.java
src/main/java/org/folio/consortia/service/impl/InventoryServiceImpl.java
src/main/java/org/folio/consortia/service/impl/SharingInstanceServiceImpl.java
src/test/java/org/folio/consortia/controller/SharingInstanceControllerIntegrationTests.java
src/test/java/org/folio/consortia/service/SharingInstanceServiceTest.java

Resolves: [MODCON-61](https://issues.folio.org/browse/MODCON-61) Implement logic to pulling down a shared instance to create shadow one in the desired tenant …

[MODCON-61] Implement logic to pulling down a shared instance to create shadow one in the desired tenant

---

pom.xml
src/main/java/org/folio/consortia/service/HttpRequestServiceImpl.java
src/main/java/org/folio/consortia/service/impl/PublicationServiceImpl.java
src/main/resources/application.yml
src/test/java/org/folio/consortia/controller/PublicationControllerTest.java
src/test/java/org/folio/consortia/service/impl/PublicationServiceImplTest.java
src/test/java/org/folio/consortia/utils/InputOutputTestUtils.java
src/test/resources/application-test.yml

* https://issues.folio.org/browse/MODCON-48
* added test in order to check correct parallel processing of tenant requests
Communication is paramount if that is to be …

MODCON-48 parallel requests test

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/consortia/controller/PublicationController.java
src/main/java/org/folio/consortia/repository/PublicationTenantRequestRepository.java
src/main/java/org/folio/consortia/service/PublicationService.java
src/main/java/org/folio/consortia/service/impl/PublicationServiceImpl.java
src/main/resources/swagger.api/publications.yaml
src/test/java/org/folio/consortia/controller/PublicationControllerTest.java
src/test/java/org/folio/consortia/service/impl/PublicationServiceImplTest.java

Resolves: [MODCON-57](https://issues.folio.org/browse/MODCON-57) Implement Delete endpoint for publication …

[MODCON-57] Implement Delete endpoint for publication

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/consortia/controller/TimerController.java
src/main/java/org/folio/consortia/repository/PublicationStatusRepository.java
src/main/java/org/folio/consortia/repository/PublicationTenantRequestRepository.java
src/main/java/org/folio/consortia/service/CleanupService.java
src/main/java/org/folio/consortia/service/impl/CleanupServiceImpl.java
src/main/java/org/folio/consortia/service/impl/TenantServiceImpl.java
src/main/resources/application.yml
src/test/java/org/folio/consortia/controller/PublicationControllerTest.java
src/test/java/org/folio/consortia/service/TenantServiceTest.java

https://issues.folio.org/browse/MODCON-58
* leveraged okapi timer interface, so scheduled jobs execute per tenant  …

MODCON-58 implemented publish coordinator cleanup

---

src/main/resources/permissions/system-user-permissions.csv

https://issues.folio.org/browse/MODCON-71

MODCON-71. Add more required permissions to system user

---

src/main/java/org/folio/consortia/service/impl/UserServiceImpl.java
src/main/resources/permissions/system-user-permissions.csv
src/test/java/org/folio/consortia/service/UserServiceTest.java

https://issues.folio.org/browse/MODCON-77

MODCON-77. Populate firstname, lastname for shadow users

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/consortia/config/AppConfig.java
src/main/java/org/folio/consortia/controller/TenantController.java
src/main/java/org/folio/consortia/domain/converter/TenantDetailsEntityToTenantConverter.java
src/main/java/org/folio/consortia/domain/converter/TenantDetailsEntityToTenantDetailsConverter.java
src/main/java/org/folio/consortia/domain/converter/TenantEntityToTenantConverter.java
src/main/java/org/folio/consortia/domain/entity/AbstractTenantEntity.java
src/main/java/org/folio/consortia/domain/entity/TenantDetailsEntity.java
src/main/java/org/folio/consortia/domain/entity/TenantEntity.java
src/main/java/org/folio/consortia/repository/TenantDetailsRepository.java
src/main/java/org/folio/consortia/service/TenantService.java
src/main/java/org/folio/consortia/service/impl/SyncPrimaryAffiliationServiceImpl.java
src/main/java/org/folio/consortia/service/impl/TenantServiceImpl.java
src/main/resources/db/changelog/changes/create-tenant-table.xml
src/main/resources/swagger.api/schemas/tenant.yaml
src/main/resources/swagger.api/tenants.yaml
src/test/java/org/folio/consortia/controller/TenantControllerTest.java
src/test/java/org/folio/consortia/service/TenantServiceTest.java
src/test/java/org/folio/consortia/service/impl/SyncPrimaryAffiliationServiceImplTest.java
src/test/java/org/folio/consortia/utils/EntityUtils.java

[MODCON-88](https://issues.folio.org/browse/MODCON-88)
Save setupStatus for Tenant and add GET endpoint to return tenant details with setup status in order to provide possibility to check setup status and add the tenants sequentially. Possible statuses;
- IN_PROGRESS: Adding tenant to the consortium is in progress, new POST requests to add another tenants is prohibited
- COMPLETED: Adding tenant is completed, can start adding next tenant
- FAILED: Some unexpected error occurred or some existing users were not affiliated. Errors should be investigated and syncAffiliations needs to be retried
Defense against concurrent requests is out of scope for this PR.
</body>
</html>
- Does this PR meet or exceed …

MODCON-88 Save setupStatus for Tenant and add GET endpoint to return tenant details with setup status

---

src/main/java/org/folio/consortia/client/PermissionsClient.java
src/main/java/org/folio/consortia/repository/UserTenantRepository.java
src/main/java/org/folio/consortia/service/PermissionUserService.java
src/main/java/org/folio/consortia/service/UserTenantService.java
src/main/java/org/folio/consortia/service/impl/PermissionUserServiceImpl.java
src/main/java/org/folio/consortia/service/impl/UserAffiliationServiceImpl.java
src/main/java/org/folio/consortia/service/impl/UserTenantServiceImpl.java
src/test/java/org/folio/consortia/service/PermissionServiceTest.java
src/test/java/org/folio/consortia/service/UserServiceTest.java
src/test/java/org/folio/consortia/service/UserTenantServiceTest.java
src/test/java/org/folio/consortia/utils/EntityUtils.java

https://issues.folio.org/browse/MODCON-89
- updated fields firstName, lastName for all shadow users for userId coming from kafka event in case when flag personalDataChanged was set to true in kafka event
- added functionality to delete corresponding permission user for each shadow user
Ideally, all …

[MODCON - 89] - Add logic to update shadow users firstName lastName

---

src/main/java/org/folio/consortia/service/LockService.java
src/main/java/org/folio/consortia/service/impl/LockServiceImpl.java
src/main/java/org/folio/consortia/service/impl/SyncPrimaryAffiliationServiceImpl.java
src/main/java/org/folio/consortia/service/impl/TenantServiceImpl.java
src/test/java/org/folio/consortia/service/LockServiceTest.java
src/test/java/org/folio/consortia/service/TenantServiceTest.java
src/test/java/org/folio/consortia/service/impl/SyncPrimaryAffiliationServiceImplTest.java

https://issues.folio.org/browse/MODCON-88
Allow only sequential processing of tenant setup operations which update db. Use transactional advisory locks for this https://www.postgresql.org/docs/current/explicit-locking.html#ADVISORY-LOCKS
Ideally, all the PRs involved in breaking changes would be …

MODCON-88 Allow only sequential processing of tenant setup operations which update db

---

src/main/java/org/folio/consortia/service/impl/SyncPrimaryAffiliationServiceImpl.java
src/test/java/org/folio/consortia/service/impl/SyncPrimaryAffiliationServiceImplTest.java
src/test/resources/mockdata/user_collection.json

https://issues.folio.org/browse/MODCON-78
Before these changes not all necessary fields were populated to user kafka payload when migration all exisitng users

MODCON-78. Add externalSystemId, barcode fields support in consortia for SAML login

---

src/main/java/org/folio/consortia/service/impl/SyncPrimaryAffiliationServiceImpl.java

…PES.SHADOW}")
Skipped patron users …

[MODCON - 103] - Skip patron users when migration existing users

---

src/main/resources/permissions/system-user-permissions.csv

https://issues.folio.org/browse/UICONSET-99

UICONSET-99. Add missing permission

---

src/main/resources/permissions/system-user-permissions.csv

https://issues.folio.org/browse/UICONSET-99
There is error 
```
{
"id": "e1e4f400-2573-43eb-9823-b04fb32fdff9",
"status": "ERROR",
"dateTime": "2023-10-03T09:35:01.535518",
"request": "{\"source\":\"consortium\",\"name\":\"ttt\",\"id\":\"f088fa06-bfec-4bb8-b4c3-1812f44ab18d\"}",
"errors": [
{
"tenantId": "college",
"errorMessage": "403 403 Forbidden: \"Access for user 'consortia-system-user' (e9e9ccda-e94a-4daa-be40-4a58453e3be3) requires permission: inventory-storage.holdings-types.item.post\"",
"errorCode": 400
},
{
"tenantId": "university",
"errorMessage": "403 403 Forbidden: \"Access for user 'consortia-system-user' (e9e9ccda-e94a-4daa-be40-4a58453e3be3) requires permission: inventory-storage.holdings-types.item.post\"",
"errorCode": 400
},
{
"tenantId": "consortium",
"errorMessage": …
```

[UICONSET-99] - Adding missing permission

---

src/main/java/org/folio/consortia/controller/SharingInstanceController.java
src/test/java/org/folio/consortia/controller/SharingInstanceControllerIntegrationTests.java
src/test/java/org/folio/consortia/controller/SharingInstanceControllerTest.java

https://issues.folio.org/browse/MODCON-94
Changed context to central tenant of tenant sending request

[MODCON-94] - Changing context from any tenant request to central tenant for GET requests

---

pom.xml

New version of folio spring base have just released 
especially as the number of inter-module and inter-team …

Updated folio spring base

---

src/main/resources/permissions/system-user-permissions.csv

https://issues.folio.org/browse/UICONSET-88
Added three missing permission
especially as the number of inter-module …

[UICONSET-88] - Added Missing permissions

---

src/main/java/org/folio/consortia/service/impl/SyncPrimaryAffiliationServiceImpl.java

https://issues.folio.org/browse/MODCON-103
Added exclusion for shadow users also …

[MODCON - 103] - Skip shadow users when migrating existing users

---

pom.xml

https://issues.folio.org/browse/MODCON-106
Updated spring boot
especially as the number of inter-module and …

[MODCON-106] - Updated folio spring boot

---

pom.xml

folio service tools dependency uppdated …

[MODCON] - folio service tools dependency uppdated

---

src/main/resources/application.yml

https://issues.folio.org/browse/MODCON-108

MODCON-108. Delete default system user password

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

[MODCON-104](https://issues.folio.org/browse/MODCON-104) - mod-consortia: module release …

[MODCON-104] - Release v1.0.0

---

NEWS.md
README.md
descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/consortia/FolioConsortiaApplication.java
src/main/resources/application.yml

Module released 
While it's helpful …

Release v1.0.2

---

README.md

Add OKAPI_URL env variable to the documentation

Add OKAPI_URL env variable to the documentation

---

src/main/resources/permissions/system-user-permissions.csv

https://issues.folio.org/browse/MODCON-122
https://issues.folio.org/browse/MODCON-121 …

[MODCON-121/122] - Added missed permissions

---

src/main/java/org/folio/consortia/client/UserTenantsClient.java
src/main/java/org/folio/consortia/domain/converter/TenantEntityToTenantConverter.java
src/main/java/org/folio/consortia/domain/entity/AbstractTenantEntity.java
src/main/java/org/folio/consortia/repository/TenantRepository.java
src/main/java/org/folio/consortia/repository/UserTenantRepository.java
src/main/java/org/folio/consortia/service/TenantService.java
src/main/java/org/folio/consortia/service/impl/SyncPrimaryAffiliationServiceImpl.java
src/main/java/org/folio/consortia/service/impl/TenantServiceImpl.java
src/main/java/org/folio/consortia/service/impl/UserTenantServiceImpl.java
src/main/resources/db/changelog/changes/create-tenant-table.xml
src/main/resources/swagger.api/schemas/tenant.yaml
src/test/java/org/folio/consortia/controller/TenantControllerTest.java
src/test/java/org/folio/consortia/controller/UserTenantControllerTest.java
src/test/java/org/folio/consortia/service/TenantServiceTest.java
src/test/java/org/folio/consortia/service/UserTenantServiceTest.java
src/test/java/org/folio/consortia/service/impl/SyncPrimaryAffiliationServiceImplTest.java
src/test/java/org/folio/consortia/utils/EntityUtils.java

https://issues.folio.org/browse/MODCON-127 …

[MODCON-127] - Implement ECS tenant soft deletion functionality

---

src/main/java/org/folio/consortia/repository/TenantRepository.java
src/main/java/org/folio/consortia/service/impl/TenantServiceImpl.java
src/test/java/org/folio/consortia/service/TenantServiceTest.java

https://issues.folio.org/browse/MODCON-130 …

[MODCON - 130] -  Added new validation for code and name uniqueness

---

NEWS.md
pom.xml
src/main/java/org/folio/consortia/repository/SharingInstanceRepository.java
src/main/java/org/folio/consortia/service/impl/SharingInstanceServiceImpl.java
src/test/java/org/folio/consortia/service/SharingInstanceServiceTest.java

Hot Fix Release v1.0.5

---

src/main/java/org/folio/consortia/service/FolioTenantService.java
src/test/java/org/folio/consortia/service/FolioTenantServiceTest.java

https://folio-org.atlassian.net/browse/MODCON-139
Using HashSet to remove duplicate permissions when user permission retrieving process. It is require to avoid error such as permission already exists
to avoid breaking …

[MODCON-139] - Fixed permissions already set issues

---

src/main/resources/swagger.api/schemas/user.yaml

The new field profilePictureLink was added to Personal object. 
https://folio-org.atlassian.net/browse/MODCON-146

[MODCON-146] Update users schema to not fail when unknown field arrives

---

NEWS.md
pom.xml

https://folio-org.atlassian.net/browse/MODCON-147
especially as the number of inter-module and inter-team …

[MODCON-147] - Release v1.1.0

---

src/main/java/org/folio/consortia/config/AppConfig.java
src/main/java/org/folio/consortia/service/impl/ConsortiumServiceImpl.java
src/main/java/org/folio/consortia/service/impl/PublicationServiceImpl.java
src/main/java/org/folio/consortia/service/impl/SharingInstanceServiceImpl.java
src/main/java/org/folio/consortia/service/impl/SyncPrimaryAffiliationServiceImpl.java
src/main/java/org/folio/consortia/service/impl/TenantServiceImpl.java
src/main/java/org/folio/consortia/service/impl/UserTenantServiceImpl.java
src/test/java/org/folio/consortia/controller/ConsortiumControllerTest.java
src/test/java/org/folio/consortia/controller/TenantControllerTest.java
src/test/java/org/folio/consortia/controller/UserTenantControllerTest.java
src/test/java/org/folio/consortia/service/ConsortiumServiceTest.java
src/test/java/org/folio/consortia/service/TenantServiceTest.java
src/test/java/org/folio/consortia/service/UserTenantServiceTest.java

https://folio-org.atlassian.net/browse/MODCON-148
Used OffsetRequest feature of Spring Data
especially as the number …

[MODCON-148] - Fix "offset" does not behaviour

---

src/main/java/org/folio/consortia/config/AppConfig.java
src/main/java/org/folio/consortia/domain/converter/UserTenantConverter.java
src/main/java/org/folio/consortia/service/impl/UserTenantServiceImpl.java
src/main/resources/swagger.api/schemas/userTenant.yaml
src/test/java/org/folio/consortia/service/UserTenantServiceTest.java

Revert deleting tenant name from this PR:
https://github.com/folio-org/mod-consortia/pull/151
because it used in UI

Revert deleting tenant name from schema

---

descriptors/ModuleDescriptor-template.json

https://folio-org.atlassian.net/browse/MODCON-155

MODCON-155. Add required Inventory: Update ownership permissions during setup only for ECS mode

---

descriptors/ModuleDescriptor-template.json

https://folio-org.atlassian.net/browse/MODCON-158

MODCON-158. Extend "Inventory: Update ownership" permission

---

descriptors/ModuleDescriptor-template.json

MODCON-162 inventory API version update

---

src/main/resources/swagger.api/sharing_instances.yaml
src/main/resources/swagger.api/tenants.yaml
src/main/resources/swagger.api/user_tenants.yaml

https://folio-org.atlassian.net/browse/MODCON-159
especially as the number of inter-module and inter-team …

[MODCON-159] - Make default limit param as 100 instead 10 all consortia endpoints

---

src/main/resources/permissions/system-user-permissions.csv

https://folio-org.atlassian.net/browse/MODCON-163
- added required POST, PUT, DELETE permissions
especially as the …

[MODCON-163] - Add system user permissions to support subject types/subject sources sharing

---

NEWS.md
PULL_REQUEST_TEMPLATE.md
descriptors/ModuleDescriptor-template.json

[MODCON-160](https://folio-org.atlassian.net/browse/MODCON-160)
According to the epic https://folio-org.atlassian.net/browse/FOLIO-4044, some permissions have been changed in the mod-source-record-storage.
mod-consortia uses the following outdated permissions:
change-manager.jobexecutions.get
change-manager.jobexecutions.put
Permission | API
-- | --
change-manager.jobExecutions.item.get | /change-manager/jobExecutions/{id}
change-manager.jobExecutions.children.collection.get | /change-manager/jobExecutions/{id}/children
change-manager.jobExecutions.item.put | /change-manager/jobExecutions/{id}
If …

MODCON-160 Rename module permissions

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

[MODCON-156](https://folio-org.atlassian.net/browse/MODCON-156) Review and cleanup Module Descriptors for mod-consortia
Permission names refactoring
Add folio-module-descriptor-validator plugin and refactor invalid permissions
[Naming convention](https://folio-org.atlassian.net/wiki/spaces/FOLIJET/pages/156368925/Permissions+naming+convention)
- Did you …

MODCON-156 Review and cleanup Module Descriptors for mod-consortia

---

pom.xml

[[MODCON-164] Update libraries of dependant acq modules to the latest versions
](https://folio-org.atlassian.net/browse/MODCON-164)
- Remove duplicate plugin

[MODCON-164] Remove duplicate plugin

---

NEWS.md
pom.xml

https://folio-org.atlassian.net/browse/FOLIO-4102
especially as the number of inter-module and inter-team …

Release v1.3.0

---

src/main/resources/permissions/admin-user-permissions.csv

Make in sync with this PR: https://github.com/folio-org/ui-users/pull/2778/files

UIU-3214 - Review and cleanup Module Descriptors for ui-users

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml
src/main/resources/permissions/admin-user-permissions.csv

Prepare Ramsons Bug Fix release 1.2.1 that includes changes for these 2 tickets:
https://folio-org.atlassian.net/browse/MODINV-1116
https://folio-org.atlassian.net/browse/UIU-3214

Release Ramsons Bug Fix 1.2.1

---

Dockerfile
Jenkinsfile
pom.xml
src/main/java/org/folio/consortia/config/FolioExecutionContextHelper.java
src/main/java/org/folio/consortia/utils/TenantContextUtils.java
src/test/java/org/folio/consortia/controller/ConsortiaConfigurationControllerTest.java
src/test/java/org/folio/consortia/controller/ConsortiumControllerTest.java
src/test/java/org/folio/consortia/controller/PublicationControllerTest.java
src/test/java/org/folio/consortia/controller/SelfControllerTest.java
src/test/java/org/folio/consortia/controller/SharingInstanceControllerIntegrationTests.java
src/test/java/org/folio/consortia/controller/SharingInstanceControllerTest.java
src/test/java/org/folio/consortia/controller/SharingSettingControllerTest.java
src/test/java/org/folio/consortia/controller/TenantControllerTest.java
src/test/java/org/folio/consortia/controller/UserTenantControllerTest.java
src/test/java/org/folio/consortia/support/BaseIT.java

[[FOLIO-4204] Update to mod-consortia Java 21](https://folio-org.atlassian.net/browse/FOLIO-4204)
Update java and dependency versions

[FOLIO-4204] Update to mod-consortia Java 21
