folio-org/mod-consortia

src/main/java/org/folio/consortia/service/impl/TenantServiceImpl.java, src/test/java/org/folio/consortia/service/TenantServiceTest.java
- We need to create dummy user tenant record only for non-central tenants
- We need to create shadow admin users only for non-central tenants
- We need to create user_tenant association for shadow admins only for non-central tenants
=> MODCON-42. Not create shadow admin and dummy user tenant for central tenant

.github/workflows/api-doc.yml, .github/workflows/api-lint.yml, .github/workflows/api-schema-lint.yml, Jenkinsfile, README.md, src/main/resources/swagger.api/consortia.yaml
[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).
=> FOLIO-3678 MODCON-54 Use GitHub Workflows api-lint and api-schema-lint and api-doc

src/main/java/org/folio/consortia/service/impl/UserAffiliationServiceImpl.java, src/test/java/org/folio/consortia/service/UserAffiliationServiceTest.java
Changes in this PR needed, because userTenantService.save (line 64) switches context to member tenant and so we need switch back to central tenant to produce CONSORTIUM_PRIMARY_AFFILIATION_CREATED.
We need to think how we can simplify context switching in future
https://issues.folio.org/browse/MODCON-50
=> [MODCON-50] - Bug Fix (Can't send kafka message)

descriptors/ModuleDescriptor-template.json, pom.xml, src/main/java/org/folio/consortia/controller/SharingInstanceController.java, src/main/java/org/folio/consortia/controller/SharingSettingController.java, src/main/java/org/folio/consortia/domain/entity/SharingSettingEntity.java, src/main/java/org/folio/consortia/repository/SharingSettingRepository.java, src/main/java/org/folio/consortia/repository/TenantRepository.java, src/main/java/org/folio/consortia/service/SharingSettingService.java, src/main/java/org/folio/consortia/service/TenantService.java, src/main/java/org/folio/consortia/service/impl/SharingInstanceServiceImpl.java, src/main/java/org/folio/consortia/service/impl/SharingSettingServiceImpl.java, src/main/java/org/folio/consortia/service/impl/TenantServiceImpl.java, src/main/java/org/folio/consortia/utils/HelperUtils.java, src/main/resources/db/changelog/changelog-master.xml, src/main/resources/db/changelog/changes/create-sharing-setting-table.xml, src/main/resources/swagger.api/schemas/sharingSetting.yaml, src/main/resources/swagger.api/sharing.yaml, src/main/resources/swagger.api/sharing_instances.yaml, src/main/resources/swagger.api/sharing_settings.yaml, src/test/java/org/folio/consortia/controller/SharingSettingControllerTest.java, src/test/java/org/folio/consortia/service/SharingSettingServiceTest.java, src/test/java/org/folio/consortia/service/TenantServiceTest.java, src/test/java/org/folio/consortia/utils/EntityUtils.java, src/test/resources/mockdata/publications/publication_request_for_setting.json, src/test/resources/mockdata/sharing_setting_request.json
https://issues.folio.org/browse/MODCON-65
I will implement 
```
Endpoint contract:
POST /consortia/<consortiumId>/sharing/settings
{
"settingId": "<UUID>",
"url": "string",
"payload": <<object>>
}
Response:
{
"createSettingsPcId": "<UUID>",
"updateSettingsPcId": "<UUID>"
}
```
based on this diagram …
=> [MODCON - 65] - Implement endpoint to save shared setting uuid in all tenants

src/main/java/org/folio/consortia/controller/PublicationController.java, src/main/java/org/folio/consortia/domain/dto/PublicationHttpResponse.java, src/main/java/org/folio/consortia/service/HttpRequestService.java, src/main/java/org/folio/consortia/service/HttpRequestServiceImpl.java, src/main/java/org/folio/consortia/service/impl/PublicationServiceImpl.java, src/test/java/org/folio/consortia/controller/PublicationControllerTest.java, src/test/java/org/folio/consortia/service/HttpRequestServiceImplTest.java, src/test/java/org/folio/consortia/service/impl/PublicationServiceImplTest.java
https://issues.folio.org/browse/MODCON-48
* fixed http status code since POST method should return 201
* Invoking `restTemplate.exchange` method with type `String.class` causes issue converting the payload. In this case StringMessageConverter used as the default and such object causes issues in all spring based modules requested by publish coordinator. As the workaround swithed ResponseEntity to type Object so JsonMessageConverter will be used instead.
verified via Karate tests https://github.com/folio-org/folio-integration-tests/pull/1022
If there are breaking changes, please **STOP** and consider …
=> MODCON-48 fixed status code

src/main/java/org/folio/consortia/config/FolioExecutionContextHelper.java, src/main/java/org/folio/consortia/service/impl/TenantServiceImpl.java, src/main/resources/log4j2-json.properties, src/main/resources/log4j2.properties, src/test/java/org/folio/consortia/config/FolioExecutionContextHelperTest.java, src/test/java/org/folio/consortia/controller/TenantControllerTest.java, src/test/java/org/folio/consortia/service/TenantServiceTest.java
In logs when creating consortia env without timeouts we saw 401 Forbidden for system user.
This PR tryis to resolve it by invalidating user permissions cache during tenants setup.
Mod-authtoken requires header Authtoken-Refresh-Cache to invalidate user permissions cache
Related commit with deleting timeouts: https://github.com/folio-org/pipelines-shared-library/commit/e93538ee2ad7f4f2877d41e1c8ab570b5c96758f 
Also loggign configured to use 1 big file to easily troubleshoot and fetch log file from Rancher.
Use Authtoken-Refresh-Cache = true to invalidate cache in mod-authtoken
=> MODCON-82. Investigate why affilitation for some users were not created by automation job without timeouts

src/main/java/org/folio/consortia/domain/entity/PublicationTenantRequestEntity.java, src/main/java/org/folio/consortia/service/HttpRequestServiceImpl.java, src/main/java/org/folio/consortia/service/impl/PublicationServiceImpl.java, src/main/java/org/folio/consortia/utils/TenantContextUtils.java, src/test/java/org/folio/consortia/service/impl/PublicationServiceImplTest.java
https://issues.folio.org/browse/MODCON-71
To fix this issue: While trying to save an object this error was occurring
```
Current thread: http-nio-8081-exec-4
19:29:58 ConsortiaAsync-2 [] [diku] [5c780098-751b-4477-9b61-0f75bc452a73] [mod-consortia] DEBUG cutionContextManager FolioExecutionContext removed;
Current thread: ConsortiaAsync-2
19:29:58 ConsortiaAsync-2 [] [diku] [5c780098-751b-4477-9b61-0f75bc452a73] [mod-consortia] ERROR blicationServiceImpl savePublicationTenantRequest:: error saving publication tenant request 541367d0-4b9f-44b3-adf8-44fe93f77f1d
org.springframework.orm.jpa.JpaObjectRetrievalFailureException: Unable to find org.folio.consortia.domain.entity.PublicationStatusEntity with id 2cd2169a-aeb1-43d1-9788-503c2f00b993
at …
```
=> [MODCON - 71] - Fixed bug relate to publish coordinator

src/main/java/org/folio/consortia/service/impl/SyncPrimaryAffiliationServiceImpl.java, src/main/resources/db/changelog/changes/create-tenant-table.xml, src/main/resources/swagger.api/schemas/tenant.yaml, src/test/java/org/folio/consortia/service/impl/SyncPrimaryAffiliationServiceImplTest.java
[MODCON-88](https://issues.folio.org/browse/MODCON-88)
add COMPLETED_WITH_ERRORS status to distinguish failures on creating primary affiliations for users
Communication …
=> MODCON-88 add COMPLETED_WITH_ERRORS status to distinguish failures on creating primary affiliations for users

src/main/java/org/folio/consortia/service/impl/TenantServiceImpl.java
When setuping job via automation pipeline it failes for some reasons(probably because of R/W split) but original transaction roll backed and status not saved to DB.
Status is always is IN_PROGRESS
=> MODCON-88. Make saving status always in new transaction

src/main/java/org/folio/consortia/domain/dto/UserType.java, src/main/java/org/folio/consortia/security/SecurityManagerService.java, src/main/java/org/folio/consortia/service/impl/SharingInstanceServiceImpl.java, src/main/java/org/folio/consortia/service/impl/SyncPrimaryAffiliationServiceImpl.java, src/main/java/org/folio/consortia/service/impl/UserAffiliationServiceImpl.java, src/main/java/org/folio/consortia/service/impl/UserServiceImpl.java, src/test/java/org/folio/consortia/security/SecurityManagerServiceTest.java, src/test/java/org/folio/consortia/service/UserServiceTest.java
https://issues.folio.org/browse/MODCON-89
- Simplify kafka consumers logic
- Use userId as partition key for user events, it can allow to distribute kafka messages accross partitions and in the same way garantee that order of event for particular user is kept
- Use sharing instance action id for Sharing Instance events, Folijet will use this key for message deduplication to not process duplicates
=> MODCON-89. Improve kafka partitions

src/main/java/org/folio/consortia/config/kafka/KafkaService.java, src/main/java/org/folio/consortia/service/PrimaryAffiliationService.java, src/main/java/org/folio/consortia/service/impl/PrimaryAffiliationServiceImpl.java, src/main/java/org/folio/consortia/service/impl/SyncPrimaryAffiliationServiceImpl.java, src/main/java/org/folio/consortia/service/impl/UserAffiliationServiceImpl.java, src/test/java/org/folio/consortia/service/PrimaryAffiliationServiceTest.java, src/test/java/org/folio/consortia/service/UserAffiliationServiceTest.java, src/test/java/org/folio/consortia/service/impl/SyncPrimaryAffiliationServiceImplTest.java
https://issues.folio.org/browse/MODCON-93
We faced an issue on Rancher when some modules created sample users without last name populated and these couple broken users rolled back the main outer transaction to affiliate all existing users, so as a result primary affiliation was not created for all users even correct.
This behaviour started to apprear after we made some changes in transactional model to levarage PostgreSql transactional advisory locks.
And this advisory lock was added to eliminate the possibility to add users from multiple  tenants simultaneously and it requires transaction, so outer transaction when we started migration all existing users were used.
Use transaction propagation REQUIRES_NEW to create a new transaction to process each individual user, in this case if some …
=> MODCON-93. Improve transaction behavior when migrating existing users to consortia

src/main/java/org/folio/consortia/config/kafka/KafkaService.java
User id is necessary for importing marc files, that invokes Sharing instances endpoints.
To do such import need to create job execution that accepts this payload:
`{
"sourceType": "ONLINE",
"userId": "a0086f7e-61b6-5c2d-9e1b-b268063a44b3"
}`
Also in folio-spring-base this userId param can be as null so added null check in this PR:
=> MODCON-93. Add userId to kafka events

src/main/resources/swagger.api/schemas/tenant.yaml
https://issues.folio.org/browse/MODCON-95
Change the limit character of the Consortia member code in the Tenant Schema that does validation
=> [MODCON-95] - Increase character limit of consortia member Code

src/main/resources/permissions/system-user-permissions.csv
https://issues.folio.org/browse/UICONSET-69
Fix this issue:
{
"id": "3e520a4c-907d-458d-90b8-f6905ee31443",
"status": "ERROR",
"dateTime": "2023-09-25T12:45:08.564458",
"request": "{\"source\":\"consortium\",\"name\":\"SharedN\",\"id\":\"00571e6e-95d6-44b8-a837-69bf15033ebc\"}",
"errors": [
{
"tenantId": "college",
"errorMessage": "403 403 Forbidden: \"Access for user 'consortia-system-user' (e9e9ccda-e94a-4daa-be40-4a58453e3be3) requires permission: inventory-storage.classification-types.item.post\"",
"errorCode": 400
},
{
"tenantId": "consortium",
"errorMessage": "403 403 Forbidden: \"Access for user 'consortia-system-user' (e9e9ccda-e94a-4daa-be40-4a58453e3be3) requires permission: inventory-storage.classification-types.item.post\"",
"errorCode": 400
},
{
"tenantId": "university", …
=> UICONSET-69. Allow user to share Inventory - Instances - Classification identifier types

descriptors/ModuleDescriptor-template.json
https://issues.folio.org/browse/MODCON-94
Created a new permission called consortia.inventory.share.local.instance and made it as visible true
=> [MODCON-94] - Add required permissions during setup only for ECS mode

src/main/java/org/folio/consortia/service/impl/SyncPrimaryAffiliationServiceImpl.java, src/main/java/org/folio/consortia/service/impl/UserAffiliationServiceImpl.java, src/main/resources/swagger.api/schemas/tenant.yaml, src/test/java/org/folio/consortia/service/UserAffiliationServiceTest.java, src/test/resources/mockdata/kafka/update_primary_affiliation_request_patron_user.json
https://issues.folio.org/browse/MODCON-101
After adding functionality to not process patron users by consortium pipeline - primary affiliations(and affiliation in central tenant) are not created. 
So now it is possible to change the user type from patron to staff - and the user should be processed by a consortium pipeline in this case.
User Updated event handler in mod-consortia should create primary affiliation(and affiliation with shadow user in central tenant if original user was from member tenant)
User Updated event handler in mod-consortia should be modified to create primary affiliation(with affiliation in central tenant if user is from member tenant).
It should invoke PrimaryAffiliationService to perform this work.
=> MODCON-101. Create primary affiliation after changing user type from patron to staff

src/main/java/org/folio/consortia/controller/SharingInstanceController.java, src/main/java/org/folio/consortia/service/impl/SharingSettingServiceImpl.java, src/test/java/org/folio/consortia/controller/SharingInstanceControllerIntegrationTests.java, src/test/java/org/folio/consortia/controller/SharingInstanceControllerTest.java
https://issues.folio.org/browse/MODCON-94
Based on Foliojet team's request relate to permission issue with local tenant, All request for start sharing request go through central tenant 
We find central tenant of local tenant and move request to central tenant context
=> [MODCON - 94] - Context change from any tenant to central tenant

descriptors/ModuleDescriptor-template.json
to provide module permissions that are used during marc instance sharing process for the POST /consortia/{consortiumId}/sharing/instances endpoint. Besides, it's necessary to extend the permissions set for instance sharing to include permission that is required for polling the status of instance sharing process on UI.
[MODCON-112](https://issues.folio.org/browse/MODCON-112)
=> MODCON-112 - Expand module permissions with permissions for sharing marc instances

README.md, descriptors/ModuleDescriptor-template.json, pom.xml, src/main/java/org/folio/consortia/FolioConsortiaApplication.java, src/main/resources/application.yml
https://issues.folio.org/browse/MODCON-114
Folio spring support has logic to reject system user without password and this fix applied into v7.2.1
https://github.com/folio-org/folio-spring-support/releases/tag/v7.2.1
=> MODCON-114. Secure setup of system users by default

descriptors/ModuleDescriptor-template.json, pom.xml
To be able to get information about linked MARC authority records when sharing local MARC instances it is needed to add inventory-storage.authorities.collection.get perm to sub-permissions for consortia.inventory.share.local.instance
Add sub permission to consortia.inventory.share.local.instanceelopers *work* with your solution in the future.
=> [MODCON-118] Add sub permission to consortia.inventory.share.local.instance

descriptors/ModuleDescriptor-template.json
to provide module permission to ensure instance update during instance sharing process for the POST /consortia/{consortiumId}/sharing/instances endpoint.
[MODCON-132](https://issues.folio.org/browse/MODCON-132)
=> MODCON-132 - Provided module permission to ensure instance update during sharing marc instances

src/main/java/org/folio/consortia/repository/SharingInstanceRepository.java, src/main/java/org/folio/consortia/service/impl/SharingInstanceServiceImpl.java, src/test/java/org/folio/consortia/service/SharingInstanceServiceTest.java
https://issues.folio.org/browse/MODCON-134
Allowed to re-share instance in case of previous attempt failed. 
Existing sharing instance record will be updated with new attempt details
=> [MODCON-134] - Allow to re-share instance after first failed attempt

src/main/java/org/folio/consortia/config/AppConfig.java, src/main/java/org/folio/consortia/domain/converter/UserTenantConverter.java, src/main/java/org/folio/consortia/service/impl/UserTenantServiceImpl.java, src/main/resources/swagger.api/schemas/userTenant.yaml, src/test/java/org/folio/consortia/service/UserTenantServiceTest.java
Also we changed serialization level from NOT_EMPTY to NOT_NULL
https://github.com/folio-org/mod-consortia/pull/149/files#diff-5bce3498556598073fd13ac15d74be95386d8743acfd9f190f8fc03de4a37172L50
https://folio-org.atlassian.net/browse/MODCON-148
Found issue
```
8:15:04 http-nio-8081-exec-5 [] [] [] [] ERROR DirectJDKLog         Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: feign.FeignException$UnprocessableEntity: [422 Unprocessable Entity] during [POST] to [http://user-tenants] [UserTenantsClient#postUserTenant(UserTenant)]: [{"errors":[{"message":"Unrecognized field \"tenantName\" (class org.folio.rest.jaxrs.model.UserTenant), not marked as ignorable (11 known properties: \"barcode\", \"tenantId\", \"userId\", …
```
=> [MODCON-148] - removed tenantName from userTenant dto & change serialization inclusing from NON_EMPTY to NON_NULL

README.md, descriptors/ModuleDescriptor-template.json, src/main/resources/application.yml
https://folio-org.atlassian.net/browse/MODCONSKC-10
TLS configuration now is supported, approach is the same as in corresponding PR in mod-search:
https://github.com/folio-org/mod-search/pull/92/files
=> MODCONSKC-10. Add support of TLS when  connecting to MSK

pom.xml, src/test/java/org/folio/consortia/support/extension/impl/KafkaContainerExtension.java
https://folio-org.atlassian.net/browse/MODCON-157
Upgrade from deprecated org.testcontainers.containers.KafkaContainer to org.testcontainers.kafka.KafkaContainer, see
https://java.testcontainers.org/modules/kafka/
Upgrade from confluentinc/cp-kafka:7.0.3 to apache/kafka-native:3.8.0, see
https://hub.docker.com/r/apache/kafka-native
Replace the deprecated KafkaContainer. Replace the heavy-weight confluentinc/cp-kafka container.
https://folio-org.atlassian.net/browse/MODCON-157
Bump testcontainers from 1.19.3 to 1.20.1.
Use new KafkaContainer.
Use apache/kafka-native.
=> MODCON-157: testcontainers.kafka.KafkaContainer, apache/kafka-native

pom.xml
[[MODCON-164] Update libraries of dependant acq modules to the latest versions
](https://folio-org.atlassian.net/browse/MODCON-164)
- Update versions
- Add module descriptor validator
=> [MODCON-164] Update libraries of dependant acq modules to the latest versions

descriptors/ModuleDescriptor-template.json
[MODINV-1116](https://folio-org.atlassian.net/browse/MODINV-1116) ECS | User with "Share" permission cannot share "Local" MARC bib record from member tenant
update invalid module permission
=> MODINV-1116 ECS | User with "Share" permission cannot share "Local" MARC bib record from member tenant

descriptors/ModuleDescriptor-template.json
to provide module permission that is required during marc instance sharing process for updating suppressFromDiscovery field of marc record.
[MODCON-174](https://folio-org.atlassian.net/browse/MODCON-174)
=> MODCON-174 - Expand module permissions with permission for sharing marc instances

src/main/java/org/folio/consortia/service/UserTenantService.java, src/main/java/org/folio/consortia/service/impl/UserAffiliationServiceImpl.java, src/main/java/org/folio/consortia/service/impl/UserTenantServiceImpl.java, src/test/java/org/folio/consortia/service/UserTenantServiceTest.java
[[MODCONSKC-61] ECS | Update Member tenant user email value on Central tenant](https://folio-org.atlassian.net/browse/MODCONSKC-61)
- Sync email and name update for users if personal data was changed
=> [MODCONSKC-61] ECS | Update Member tenant user email value on Central tenant
